// Minimal browser + worker + node globals, avoids depending on the `globals` package.
export default {
  window: "readonly",
  document: "readonly",
  navigator: "readonly",
  console: "readonly",
  fetch: "readonly",
  crypto: "readonly",
  URL: "readonly",
  Blob: "readonly",
  FileReader: "readonly",
  localStorage: "readonly",
  indexedDB: "readonly",
  self: "readonly",
  postMessage: "readonly",
  Worker: "readonly",
  performance: "readonly",
  setTimeout: "readonly",
  clearTimeout: "readonly",
  process: "readonly",
  __dirname: "readonly",
  module: "readonly",
  require: "readonly",
};
